// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using MyWay.EF;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace MyWay.EF.Migrations
{
    [DbContext(typeof(MyWayDbContext))]
    [Migration("20260707185047_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.28")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("MyWay.Core.CarrierListings.CarrierListing", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid?>("CarrierCompanyId")
                        .HasColumnType("uuid")
                        .HasColumnName("carrier_company_id");

                    b.Property<Guid>("CarrierProfileId")
                        .HasColumnType("uuid")
                        .HasColumnName("carrier_profile_id");

                    b.Property<Guid?>("CarrierUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("carrier_user_id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Description")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)")
                        .HasColumnName("description");

                    b.Property<bool>("IsVisibleOnCarrierBoardIndex")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("boolean")
                        .HasColumnName("is_visible_on_carrier_board")
                        .HasComputedColumnSql("status = 'Available'", true);

                    b.Property<DateTimeOffset?>("LastStatusChangedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_status_changed_at");

                    b.Property<DateTimeOffset?>("PublishedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("published_at");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("status");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("title");

                    b.HasKey("Id");

                    b.HasIndex("Status", "CarrierUserId", "CarrierCompanyId", "IsVisibleOnCarrierBoardIndex");

                    b.ToTable("carrier_listings", (string)null);
                });

            modelBuilder.Entity("MyWay.Core.Companies.Company", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid>("CreatedByUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("created_by_user_id");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<string>("LegalName")
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)")
                        .HasColumnName("legal_name");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("name");

                    b.Property<string>("TaxNumber")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("tax_number");

                    b.HasKey("Id");

                    b.ToTable("companies", (string)null);
                });

            modelBuilder.Entity("MyWay.Core.Companies.CompanyMember", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("CompanyId")
                        .HasColumnType("uuid")
                        .HasColumnName("company_id");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<DateTimeOffset>("JoinedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("joined_at");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("role");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id");

                    b.HasIndex("CompanyId", "UserId", "IsActive");

                    b.ToTable("company_members", (string)null);
                });

            modelBuilder.Entity("MyWay.Core.Profiles.CarrierProfile", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid?>("CompanyId")
                        .HasColumnType("uuid")
                        .HasColumnName("company_id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Description")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)")
                        .HasColumnName("description");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("display_name");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<Guid?>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id");

                    b.ToTable("carrier_profiles", (string)null);
                });

            modelBuilder.Entity("MyWay.Core.Profiles.CustomerProfile", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("display_name");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id");

                    b.ToTable("customer_profiles", (string)null);
                });

            modelBuilder.Entity("MyWay.Core.Profiles.DriverProfile", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("display_name");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<string>("LicenseNumber")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("license_number");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id");

                    b.ToTable("driver_profiles", (string)null);
                });

            modelBuilder.Entity("MyWay.Core.Resources.ResourceReservation", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset?>("CancelledAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("cancelled_at");

                    b.Property<DateTimeOffset?>("CompletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("completed_at");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid?>("DriverUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("driver_user_id");

                    b.Property<Guid>("ShipmentOrderId")
                        .HasColumnType("uuid")
                        .HasColumnName("shipment_order_id");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("status");

                    b.Property<Guid?>("VehicleId")
                        .HasColumnType("uuid")
                        .HasColumnName("vehicle_id");

                    b.HasKey("Id");

                    b.HasIndex("Status", "DriverUserId", "VehicleId", "ShipmentOrderId");

                    b.ToTable("resource_reservations", (string)null);
                });

            modelBuilder.Entity("MyWay.Core.Reviews.Review", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid>("FromUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("from_user_id");

                    b.Property<int>("Rating")
                        .HasColumnType("integer")
                        .HasColumnName("rating");

                    b.Property<Guid>("ShipmentOrderId")
                        .HasColumnType("uuid")
                        .HasColumnName("shipment_order_id");

                    b.Property<Guid>("TargetId")
                        .HasColumnType("uuid")
                        .HasColumnName("target_id");

                    b.Property<string>("TargetType")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("target_type");

                    b.Property<string>("Text")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)")
                        .HasColumnName("text");

                    b.HasKey("Id");

                    b.HasIndex("ShipmentOrderId", "TargetType", "TargetId");

                    b.ToTable("reviews", (string)null);
                });

            modelBuilder.Entity("MyWay.Core.Shipments.ShipmentOffer", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset?>("AcceptedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("accepted_at");

                    b.Property<Guid?>("CarrierCompanyId")
                        .HasColumnType("uuid")
                        .HasColumnName("carrier_company_id");

                    b.Property<Guid?>("CarrierUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("carrier_user_id");

                    b.Property<string>("Comment")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("comment");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid>("CreatedByUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("created_by_user_id");

                    b.Property<DateTimeOffset?>("RejectedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("rejected_at");

                    b.Property<Guid>("ShipmentRequestId")
                        .HasColumnType("uuid")
                        .HasColumnName("shipment_request_id");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("status");

                    b.Property<DateTimeOffset?>("WithdrawnAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("withdrawn_at");

                    b.HasKey("Id");

                    b.HasIndex("ShipmentRequestId", "Status", "CarrierUserId", "CarrierCompanyId");

                    b.ToTable("shipment_offers", (string)null);
                });

            modelBuilder.Entity("MyWay.Core.Shipments.ShipmentOrder", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("AcceptedOfferId")
                        .HasColumnType("uuid")
                        .HasColumnName("accepted_offer_id");

                    b.Property<Guid?>("AssignedDriverUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("assigned_driver_user_id");

                    b.Property<Guid?>("AssignedVehicleId")
                        .HasColumnType("uuid")
                        .HasColumnName("assigned_vehicle_id");

                    b.Property<string>("CancellationReason")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("cancellation_reason");

                    b.Property<DateTimeOffset?>("CancelledAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("cancelled_at");

                    b.Property<Guid?>("CarrierCompanyId")
                        .HasColumnType("uuid")
                        .HasColumnName("carrier_company_id");

                    b.Property<Guid?>("CarrierUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("carrier_user_id");

                    b.Property<DateTimeOffset?>("CompletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("completed_at");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid>("CreatedByUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("created_by_user_id");

                    b.Property<Guid?>("CustomerCompanyId")
                        .HasColumnType("uuid")
                        .HasColumnName("customer_company_id");

                    b.Property<Guid?>("CustomerUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("customer_user_id");

                    b.Property<DateTimeOffset?>("DeliveredAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("delivered_at");

                    b.Property<DateTimeOffset>("PlannedDeliveryAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("planned_delivery_at");

                    b.Property<DateTimeOffset>("PlannedPickupAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("planned_pickup_at");

                    b.Property<decimal?>("PlatformCommissionPercent")
                        .HasPrecision(5, 2)
                        .HasColumnType("numeric(5,2)")
                        .HasColumnName("platform_commission_percent");

                    b.Property<Guid>("ShipmentRequestId")
                        .HasColumnType("uuid")
                        .HasColumnName("shipment_request_id");

                    b.Property<DateTimeOffset?>("StartedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("started_at");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("status");

                    b.HasKey("Id");

                    b.HasIndex("Status", "CustomerUserId", "CustomerCompanyId", "CarrierUserId", "CarrierCompanyId");

                    b.ToTable("shipment_orders", (string)null);
                });

            modelBuilder.Entity("MyWay.Core.Shipments.ShipmentRequest", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid?>("AcceptedOfferId")
                        .HasColumnType("uuid")
                        .HasColumnName("accepted_offer_id");

                    b.Property<string>("CancellationReason")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("cancellation_reason");

                    b.Property<DateTimeOffset?>("CancelledAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("cancelled_at");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid>("CreatedByUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("created_by_user_id");

                    b.Property<Guid?>("CustomerCompanyId")
                        .HasColumnType("uuid")
                        .HasColumnName("customer_company_id");

                    b.Property<Guid?>("CustomerUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("customer_user_id");

                    b.Property<DateTimeOffset>("PlannedDeliveryAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("planned_delivery_at");

                    b.Property<DateTimeOffset>("PlannedPickupAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("planned_pickup_at");

                    b.Property<DateTimeOffset?>("PublishedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("published_at");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("status");

                    b.Property<Guid?>("TargetCarrierListingId")
                        .HasColumnType("uuid")
                        .HasColumnName("target_carrier_listing_id");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("type");

                    b.HasKey("Id");

                    b.HasIndex("Status", "Type", "CreatedAt", "PublishedAt");

                    b.ToTable("shipment_requests", (string)null);
                });

            modelBuilder.Entity("MyWay.Core.Users.User", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("AuthUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("auth_user_id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("display_name");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(320)
                        .HasColumnType("character varying(320)")
                        .HasColumnName("email");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<string>("PhoneNumber")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("phone_number");

                    b.HasKey("Id");

                    b.ToTable("users", (string)null);
                });

            modelBuilder.Entity("MyWay.Core.Vehicles.Vehicle", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Brand")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("brand");

                    b.Property<decimal>("CapacityKg")
                        .HasPrecision(18, 3)
                        .HasColumnType("numeric(18,3)")
                        .HasColumnName("capacity_kg");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<string>("Model")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("model");

                    b.Property<Guid?>("OwnerCompanyId")
                        .HasColumnType("uuid")
                        .HasColumnName("owner_company_id");

                    b.Property<Guid?>("OwnerUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("owner_user_id");

                    b.Property<string>("PlateNumber")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("plate_number");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("type");

                    b.Property<decimal?>("VolumeM3")
                        .HasPrecision(18, 3)
                        .HasColumnType("numeric(18,3)")
                        .HasColumnName("volume_m3");

                    b.HasKey("Id");

                    b.ToTable("vehicles", (string)null);
                });

            modelBuilder.Entity("MyWay.Core.Warehouses.Warehouse", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("DriverComment")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("driver_comment");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("name");

                    b.Property<Guid?>("OwnerCompanyId")
                        .HasColumnType("uuid")
                        .HasColumnName("owner_company_id");

                    b.Property<Guid?>("OwnerUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("owner_user_id");

                    b.Property<string>("WorkingHours")
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)")
                        .HasColumnName("working_hours");

                    b.HasKey("Id");

                    b.ToTable("warehouses", (string)null);
                });

            modelBuilder.Entity("MyWay.Core.Waybills.Waybill", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("CancellationReason")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("cancellation_reason");

                    b.Property<DateTimeOffset?>("CancelledAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("cancelled_at");

                    b.Property<Guid?>("CarrierCompanyId")
                        .HasColumnType("uuid")
                        .HasColumnName("carrier_company_id");

                    b.Property<Guid?>("CarrierUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("carrier_user_id");

                    b.Property<DateTimeOffset?>("ClosedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("closed_at");

                    b.Property<string>("Comment")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("comment");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid?>("CustomerCompanyId")
                        .HasColumnType("uuid")
                        .HasColumnName("customer_company_id");

                    b.Property<Guid?>("CustomerUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("customer_user_id");

                    b.Property<string>("DriverLicenseNumber")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("driver_license_number");

                    b.Property<string>("DriverName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("driver_name");

                    b.Property<Guid>("DriverUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("driver_user_id");

                    b.Property<DateTimeOffset?>("IssuedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("issued_at");

                    b.Property<string>("Number")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("number");

                    b.Property<decimal?>("OdometerEndKm")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)")
                        .HasColumnName("odometer_end_km");

                    b.Property<decimal?>("OdometerStartKm")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)")
                        .HasColumnName("odometer_start_km");

                    b.Property<Guid>("ShipmentOrderId")
                        .HasColumnType("uuid")
                        .HasColumnName("shipment_order_id");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("status");

                    b.Property<string>("VehicleBrand")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("vehicle_brand");

                    b.Property<Guid>("VehicleId")
                        .HasColumnType("uuid")
                        .HasColumnName("vehicle_id");

                    b.Property<string>("VehicleModel")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("vehicle_model");

                    b.Property<string>("VehiclePlateNumber")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("vehicle_plate_number");

                    b.HasKey("Id");

                    b.HasIndex("ShipmentOrderId", "Status");

                    b.ToTable("waybills", (string)null);
                });

            modelBuilder.Entity("MyWay.Core.CarrierListings.CarrierListing", b =>
                {
                    b.OwnsOne("MyWay.Core.Common.ValueObjects.Money", "BasePrice", b1 =>
                        {
                            b1.Property<Guid>("CarrierListingId")
                                .HasColumnType("uuid");

                            b1.Property<decimal>("Amount")
                                .HasPrecision(18, 2)
                                .HasColumnType("numeric(18,2)")
                                .HasColumnName("base_price_amount");

                            b1.Property<string>("Currency")
                                .HasMaxLength(3)
                                .HasColumnType("character varying(3)")
                                .HasColumnName("base_price_currency");

                            b1.HasKey("CarrierListingId");

                            b1.ToTable("carrier_listings");

                            b1.WithOwner()
                                .HasForeignKey("CarrierListingId");
                        });

                    b.Navigation("BasePrice");
                });

            modelBuilder.Entity("MyWay.Core.Companies.Company", b =>
                {
                    b.OwnsOne("MyWay.Core.Common.ValueObjects.Address", "Address", b1 =>
                        {
                            b1.Property<Guid>("CompanyId")
                                .HasColumnType("uuid");

                            b1.Property<string>("ApartmentOrOffice")
                                .HasMaxLength(64)
                                .HasColumnType("character varying(64)")
                                .HasColumnName("address_apartment_or_office");

                            b1.Property<string>("City")
                                .HasMaxLength(128)
                                .HasColumnType("character varying(128)")
                                .HasColumnName("address_city");

                            b1.Property<string>("Country")
                                .HasMaxLength(128)
                                .HasColumnType("character varying(128)")
                                .HasColumnName("address_country");

                            b1.Property<string>("House")
                                .HasMaxLength(64)
                                .HasColumnType("character varying(64)")
                                .HasColumnName("address_house");

                            b1.Property<decimal?>("Latitude")
                                .HasPrecision(9, 6)
                                .HasColumnType("numeric(9,6)")
                                .HasColumnName("address_latitude");

                            b1.Property<decimal?>("Longitude")
                                .HasPrecision(9, 6)
                                .HasColumnType("numeric(9,6)")
                                .HasColumnName("address_longitude");

                            b1.Property<string>("PostalCode")
                                .HasMaxLength(32)
                                .HasColumnType("character varying(32)")
                                .HasColumnName("address_postal_code");

                            b1.Property<string>("Region")
                                .HasMaxLength(128)
                                .HasColumnType("character varying(128)")
                                .HasColumnName("address_region");

                            b1.Property<string>("Street")
                                .HasMaxLength(256)
                                .HasColumnType("character varying(256)")
                                .HasColumnName("address_street");

                            b1.HasKey("CompanyId");

                            b1.ToTable("companies");

                            b1.WithOwner()
                                .HasForeignKey("CompanyId");
                        });

                    b.OwnsOne("MyWay.Core.Common.ValueObjects.ContactInfo", "ContactInfo", b1 =>
                        {
                            b1.Property<Guid>("CompanyId")
                                .HasColumnType("uuid");

                            b1.Property<string>("ContactName")
                                .HasMaxLength(256)
                                .HasColumnType("character varying(256)")
                                .HasColumnName("contact_person_name");

                            b1.Property<string>("Email")
                                .HasMaxLength(320)
                                .HasColumnType("character varying(320)")
                                .HasColumnName("contact_email");

                            b1.Property<string>("Phone")
                                .HasMaxLength(64)
                                .HasColumnType("character varying(64)")
                                .HasColumnName("contact_phone");

                            b1.HasKey("CompanyId");

                            b1.ToTable("companies");

                            b1.WithOwner()
                                .HasForeignKey("CompanyId");
                        });

                    b.Navigation("Address");

                    b.Navigation("ContactInfo");
                });

            modelBuilder.Entity("MyWay.Core.Resources.ResourceReservation", b =>
                {
                    b.OwnsOne("MyWay.Core.Common.ValueObjects.DateRange", "Period", b1 =>
                        {
                            b1.Property<Guid>("ResourceReservationId")
                                .HasColumnType("uuid");

                            b1.Property<DateTimeOffset>("EndAt")
                                .HasColumnType("timestamp with time zone")
                                .HasColumnName("period_end");

                            b1.Property<DateTimeOffset>("StartAt")
                                .HasColumnType("timestamp with time zone")
                                .HasColumnName("period_start");

                            b1.HasKey("ResourceReservationId");

                            b1.ToTable("resource_reservations");

                            b1.WithOwner()
                                .HasForeignKey("ResourceReservationId");
                        });

                    b.Navigation("Period")
                        .IsRequired();
                });

            modelBuilder.Entity("MyWay.Core.Shipments.ShipmentOffer", b =>
                {
                    b.OwnsOne("MyWay.Core.Common.ValueObjects.Money", "OfferedPrice", b1 =>
                        {
                            b1.Property<Guid>("ShipmentOfferId")
                                .HasColumnType("uuid");

                            b1.Property<decimal>("Amount")
                                .HasPrecision(18, 2)
                                .HasColumnType("numeric(18,2)")
                                .HasColumnName("carrier_price_amount");

                            b1.Property<string>("Currency")
                                .IsRequired()
                                .HasMaxLength(3)
                                .HasColumnType("character varying(3)")
                                .HasColumnName("carrier_price_currency");

                            b1.HasKey("ShipmentOfferId");

                            b1.ToTable("shipment_offers");

                            b1.WithOwner()
                                .HasForeignKey("ShipmentOfferId");
                        });

                    b.Navigation("OfferedPrice")
                        .IsRequired();
                });

            modelBuilder.Entity("MyWay.Core.Shipments.ShipmentOrder", b =>
                {
                    b.OwnsOne("MyWay.Core.Common.ValueObjects.CargoDetails", "CargoDetails", b1 =>
                        {
                            b1.Property<Guid>("ShipmentOrderId")
                                .HasColumnType("uuid");

                            b1.Property<string>("Description")
                                .HasMaxLength(1000)
                                .HasColumnType("character varying(1000)")
                                .HasColumnName("cargo_description");

                            b1.Property<decimal?>("HeightCm")
                                .HasPrecision(18, 3)
                                .HasColumnType("numeric(18,3)")
                                .HasColumnName("cargo_height_cm");

                            b1.Property<bool>("IsFragile")
                                .HasColumnType("boolean")
                                .HasColumnName("cargo_is_fragile");

                            b1.Property<decimal?>("LengthCm")
                                .HasPrecision(18, 3)
                                .HasColumnType("numeric(18,3)")
                                .HasColumnName("cargo_length_cm");

                            b1.Property<string>("Name")
                                .IsRequired()
                                .HasMaxLength(256)
                                .HasColumnType("character varying(256)")
                                .HasColumnName("cargo_name");

                            b1.Property<bool>("RequiresRefrigeration")
                                .HasColumnType("boolean")
                                .HasColumnName("cargo_requires_refrigeration");

                            b1.Property<decimal?>("VolumeM3")
                                .HasPrecision(18, 3)
                                .HasColumnType("numeric(18,3)")
                                .HasColumnName("cargo_volume_m3");

                            b1.Property<decimal>("WeightKg")
                                .HasPrecision(18, 3)
                                .HasColumnType("numeric(18,3)")
                                .HasColumnName("cargo_weight_kg");

                            b1.Property<decimal?>("WidthCm")
                                .HasPrecision(18, 3)
                                .HasColumnType("numeric(18,3)")
                                .HasColumnName("cargo_width_cm");

                            b1.HasKey("ShipmentOrderId");

                            b1.ToTable("shipment_orders");

                            b1.WithOwner()
                                .HasForeignKey("ShipmentOrderId");
                        });

                    b.OwnsOne("MyWay.Core.Common.ValueObjects.Address", "DeliveryAddress", b1 =>
                        {
                            b1.Property<Guid>("ShipmentOrderId")
                                .HasColumnType("uuid");

                            b1.Property<string>("ApartmentOrOffice")
                                .HasMaxLength(64)
                                .HasColumnType("character varying(64)")
                                .HasColumnName("delivery_apartment_or_office");

                            b1.Property<string>("City")
                                .IsRequired()
                                .HasMaxLength(128)
                                .HasColumnType("character varying(128)")
                                .HasColumnName("delivery_city");

                            b1.Property<string>("Country")
                                .IsRequired()
                                .HasMaxLength(128)
                                .HasColumnType("character varying(128)")
                                .HasColumnName("delivery_country");

                            b1.Property<string>("House")
                                .IsRequired()
                                .HasMaxLength(64)
                                .HasColumnType("character varying(64)")
                                .HasColumnName("delivery_house");

                            b1.Property<decimal?>("Latitude")
                                .HasPrecision(9, 6)
                                .HasColumnType("numeric(9,6)")
                                .HasColumnName("delivery_latitude");

                            b1.Property<decimal?>("Longitude")
                                .HasPrecision(9, 6)
                                .HasColumnType("numeric(9,6)")
                                .HasColumnName("delivery_longitude");

                            b1.Property<string>("PostalCode")
                                .HasMaxLength(32)
                                .HasColumnType("character varying(32)")
                                .HasColumnName("delivery_postal_code");

                            b1.Property<string>("Region")
                                .HasMaxLength(128)
                                .HasColumnType("character varying(128)")
                                .HasColumnName("delivery_region");

                            b1.Property<string>("Street")
                                .IsRequired()
                                .HasMaxLength(256)
                                .HasColumnType("character varying(256)")
                                .HasColumnName("delivery_street");

                            b1.HasKey("ShipmentOrderId");

                            b1.ToTable("shipment_orders");

                            b1.WithOwner()
                                .HasForeignKey("ShipmentOrderId");
                        });

                    b.OwnsOne("MyWay.Core.Common.ValueObjects.Money", "FinalPrice", b1 =>
                        {
                            b1.Property<Guid>("ShipmentOrderId")
                                .HasColumnType("uuid");

                            b1.Property<decimal>("Amount")
                                .HasPrecision(18, 2)
                                .HasColumnType("numeric(18,2)")
                                .HasColumnName("final_price_amount");

                            b1.Property<string>("Currency")
                                .IsRequired()
                                .HasMaxLength(3)
                                .HasColumnType("character varying(3)")
                                .HasColumnName("final_price_currency");

                            b1.HasKey("ShipmentOrderId");

                            b1.ToTable("shipment_orders");

                            b1.WithOwner()
                                .HasForeignKey("ShipmentOrderId");
                        });

                    b.OwnsOne("MyWay.Core.Common.ValueObjects.Address", "PickupAddress", b1 =>
                        {
                            b1.Property<Guid>("ShipmentOrderId")
                                .HasColumnType("uuid");

                            b1.Property<string>("ApartmentOrOffice")
                                .HasMaxLength(64)
                                .HasColumnType("character varying(64)")
                                .HasColumnName("pickup_apartment_or_office");

                            b1.Property<string>("City")
                                .IsRequired()
                                .HasMaxLength(128)
                                .HasColumnType("character varying(128)")
                                .HasColumnName("pickup_city");

                            b1.Property<string>("Country")
                                .IsRequired()
                                .HasMaxLength(128)
                                .HasColumnType("character varying(128)")
                                .HasColumnName("pickup_country");

                            b1.Property<string>("House")
                                .IsRequired()
                                .HasMaxLength(64)
                                .HasColumnType("character varying(64)")
                                .HasColumnName("pickup_house");

                            b1.Property<decimal?>("Latitude")
                                .HasPrecision(9, 6)
                                .HasColumnType("numeric(9,6)")
                                .HasColumnName("pickup_latitude");

                            b1.Property<decimal?>("Longitude")
                                .HasPrecision(9, 6)
                                .HasColumnType("numeric(9,6)")
                                .HasColumnName("pickup_longitude");

                            b1.Property<string>("PostalCode")
                                .HasMaxLength(32)
                                .HasColumnType("character varying(32)")
                                .HasColumnName("pickup_postal_code");

                            b1.Property<string>("Region")
                                .HasMaxLength(128)
                                .HasColumnType("character varying(128)")
                                .HasColumnName("pickup_region");

                            b1.Property<string>("Street")
                                .IsRequired()
                                .HasMaxLength(256)
                                .HasColumnType("character varying(256)")
                                .HasColumnName("pickup_street");

                            b1.HasKey("ShipmentOrderId");

                            b1.ToTable("shipment_orders");

                            b1.WithOwner()
                                .HasForeignKey("ShipmentOrderId");
                        });

                    b.OwnsOne("MyWay.Core.Common.ValueObjects.Money", "PlatformCommissionAmount", b1 =>
                        {
                            b1.Property<Guid>("ShipmentOrderId")
                                .HasColumnType("uuid");

                            b1.Property<decimal>("Amount")
                                .HasPrecision(18, 2)
                                .HasColumnType("numeric(18,2)")
                                .HasColumnName("platform_commission_amount");

                            b1.Property<string>("Currency")
                                .HasMaxLength(3)
                                .HasColumnType("character varying(3)")
                                .HasColumnName("platform_commission_currency");

                            b1.HasKey("ShipmentOrderId");

                            b1.ToTable("shipment_orders");

                            b1.WithOwner()
                                .HasForeignKey("ShipmentOrderId");
                        });

                    b.Navigation("CargoDetails")
                        .IsRequired();

                    b.Navigation("DeliveryAddress")
                        .IsRequired();

                    b.Navigation("FinalPrice")
                        .IsRequired();

                    b.Navigation("PickupAddress")
                        .IsRequired();

                    b.Navigation("PlatformCommissionAmount");
                });

            modelBuilder.Entity("MyWay.Core.Shipments.ShipmentRequest", b =>
                {
                    b.OwnsOne("MyWay.Core.Common.ValueObjects.CargoDetails", "CargoDetails", b1 =>
                        {
                            b1.Property<Guid>("ShipmentRequestId")
                                .HasColumnType("uuid");

                            b1.Property<string>("Description")
                                .HasMaxLength(1000)
                                .HasColumnType("character varying(1000)")
                                .HasColumnName("cargo_description");

                            b1.Property<decimal?>("HeightCm")
                                .HasPrecision(18, 3)
                                .HasColumnType("numeric(18,3)")
                                .HasColumnName("cargo_height_cm");

                            b1.Property<bool>("IsFragile")
                                .HasColumnType("boolean")
                                .HasColumnName("cargo_is_fragile");

                            b1.Property<decimal?>("LengthCm")
                                .HasPrecision(18, 3)
                                .HasColumnType("numeric(18,3)")
                                .HasColumnName("cargo_length_cm");

                            b1.Property<string>("Name")
                                .IsRequired()
                                .HasMaxLength(256)
                                .HasColumnType("character varying(256)")
                                .HasColumnName("cargo_name");

                            b1.Property<bool>("RequiresRefrigeration")
                                .HasColumnType("boolean")
                                .HasColumnName("cargo_requires_refrigeration");

                            b1.Property<decimal?>("VolumeM3")
                                .HasPrecision(18, 3)
                                .HasColumnType("numeric(18,3)")
                                .HasColumnName("cargo_volume_m3");

                            b1.Property<decimal>("WeightKg")
                                .HasPrecision(18, 3)
                                .HasColumnType("numeric(18,3)")
                                .HasColumnName("cargo_weight_kg");

                            b1.Property<decimal?>("WidthCm")
                                .HasPrecision(18, 3)
                                .HasColumnType("numeric(18,3)")
                                .HasColumnName("cargo_width_cm");

                            b1.HasKey("ShipmentRequestId");

                            b1.ToTable("shipment_requests");

                            b1.WithOwner()
                                .HasForeignKey("ShipmentRequestId");
                        });

                    b.OwnsOne("MyWay.Core.Common.ValueObjects.Money", "CustomerPrice", b1 =>
                        {
                            b1.Property<Guid>("ShipmentRequestId")
                                .HasColumnType("uuid");

                            b1.Property<decimal>("Amount")
                                .HasPrecision(18, 2)
                                .HasColumnType("numeric(18,2)")
                                .HasColumnName("customer_price_amount");

                            b1.Property<string>("Currency")
                                .IsRequired()
                                .HasMaxLength(3)
                                .HasColumnType("character varying(3)")
                                .HasColumnName("customer_price_currency");

                            b1.HasKey("ShipmentRequestId");

                            b1.ToTable("shipment_requests");

                            b1.WithOwner()
                                .HasForeignKey("ShipmentRequestId");
                        });

                    b.OwnsOne("MyWay.Core.Common.ValueObjects.Address", "DeliveryAddress", b1 =>
                        {
                            b1.Property<Guid>("ShipmentRequestId")
                                .HasColumnType("uuid");

                            b1.Property<string>("ApartmentOrOffice")
                                .HasMaxLength(64)
                                .HasColumnType("character varying(64)")
                                .HasColumnName("delivery_apartment_or_office");

                            b1.Property<string>("City")
                                .IsRequired()
                                .HasMaxLength(128)
                                .HasColumnType("character varying(128)")
                                .HasColumnName("delivery_city");

                            b1.Property<string>("Country")
                                .IsRequired()
                                .HasMaxLength(128)
                                .HasColumnType("character varying(128)")
                                .HasColumnName("delivery_country");

                            b1.Property<string>("House")
                                .IsRequired()
                                .HasMaxLength(64)
                                .HasColumnType("character varying(64)")
                                .HasColumnName("delivery_house");

                            b1.Property<decimal?>("Latitude")
                                .HasPrecision(9, 6)
                                .HasColumnType("numeric(9,6)")
                                .HasColumnName("delivery_latitude");

                            b1.Property<decimal?>("Longitude")
                                .HasPrecision(9, 6)
                                .HasColumnType("numeric(9,6)")
                                .HasColumnName("delivery_longitude");

                            b1.Property<string>("PostalCode")
                                .HasMaxLength(32)
                                .HasColumnType("character varying(32)")
                                .HasColumnName("delivery_postal_code");

                            b1.Property<string>("Region")
                                .HasMaxLength(128)
                                .HasColumnType("character varying(128)")
                                .HasColumnName("delivery_region");

                            b1.Property<string>("Street")
                                .IsRequired()
                                .HasMaxLength(256)
                                .HasColumnType("character varying(256)")
                                .HasColumnName("delivery_street");

                            b1.HasKey("ShipmentRequestId");

                            b1.ToTable("shipment_requests");

                            b1.WithOwner()
                                .HasForeignKey("ShipmentRequestId");
                        });

                    b.OwnsOne("MyWay.Core.Common.ValueObjects.Address", "PickupAddress", b1 =>
                        {
                            b1.Property<Guid>("ShipmentRequestId")
                                .HasColumnType("uuid");

                            b1.Property<string>("ApartmentOrOffice")
                                .HasMaxLength(64)
                                .HasColumnType("character varying(64)")
                                .HasColumnName("pickup_apartment_or_office");

                            b1.Property<string>("City")
                                .IsRequired()
                                .HasMaxLength(128)
                                .HasColumnType("character varying(128)")
                                .HasColumnName("pickup_city");

                            b1.Property<string>("Country")
                                .IsRequired()
                                .HasMaxLength(128)
                                .HasColumnType("character varying(128)")
                                .HasColumnName("pickup_country");

                            b1.Property<string>("House")
                                .IsRequired()
                                .HasMaxLength(64)
                                .HasColumnType("character varying(64)")
                                .HasColumnName("pickup_house");

                            b1.Property<decimal?>("Latitude")
                                .HasPrecision(9, 6)
                                .HasColumnType("numeric(9,6)")
                                .HasColumnName("pickup_latitude");

                            b1.Property<decimal?>("Longitude")
                                .HasPrecision(9, 6)
                                .HasColumnType("numeric(9,6)")
                                .HasColumnName("pickup_longitude");

                            b1.Property<string>("PostalCode")
                                .HasMaxLength(32)
                                .HasColumnType("character varying(32)")
                                .HasColumnName("pickup_postal_code");

                            b1.Property<string>("Region")
                                .HasMaxLength(128)
                                .HasColumnType("character varying(128)")
                                .HasColumnName("pickup_region");

                            b1.Property<string>("Street")
                                .IsRequired()
                                .HasMaxLength(256)
                                .HasColumnType("character varying(256)")
                                .HasColumnName("pickup_street");

                            b1.HasKey("ShipmentRequestId");

                            b1.ToTable("shipment_requests");

                            b1.WithOwner()
                                .HasForeignKey("ShipmentRequestId");
                        });

                    b.Navigation("CargoDetails")
                        .IsRequired();

                    b.Navigation("CustomerPrice")
                        .IsRequired();

                    b.Navigation("DeliveryAddress")
                        .IsRequired();

                    b.Navigation("PickupAddress")
                        .IsRequired();
                });

            modelBuilder.Entity("MyWay.Core.Warehouses.Warehouse", b =>
                {
                    b.OwnsOne("MyWay.Core.Common.ValueObjects.Address", "Address", b1 =>
                        {
                            b1.Property<Guid>("WarehouseId")
                                .HasColumnType("uuid");

                            b1.Property<string>("ApartmentOrOffice")
                                .HasMaxLength(64)
                                .HasColumnType("character varying(64)")
                                .HasColumnName("address_apartment_or_office");

                            b1.Property<string>("City")
                                .IsRequired()
                                .HasMaxLength(128)
                                .HasColumnType("character varying(128)")
                                .HasColumnName("address_city");

                            b1.Property<string>("Country")
                                .IsRequired()
                                .HasMaxLength(128)
                                .HasColumnType("character varying(128)")
                                .HasColumnName("address_country");

                            b1.Property<string>("House")
                                .IsRequired()
                                .HasMaxLength(64)
                                .HasColumnType("character varying(64)")
                                .HasColumnName("address_house");

                            b1.Property<decimal?>("Latitude")
                                .HasPrecision(9, 6)
                                .HasColumnType("numeric(9,6)")
                                .HasColumnName("address_latitude");

                            b1.Property<decimal?>("Longitude")
                                .HasPrecision(9, 6)
                                .HasColumnType("numeric(9,6)")
                                .HasColumnName("address_longitude");

                            b1.Property<string>("PostalCode")
                                .HasMaxLength(32)
                                .HasColumnType("character varying(32)")
                                .HasColumnName("address_postal_code");

                            b1.Property<string>("Region")
                                .HasMaxLength(128)
                                .HasColumnType("character varying(128)")
                                .HasColumnName("address_region");

                            b1.Property<string>("Street")
                                .IsRequired()
                                .HasMaxLength(256)
                                .HasColumnType("character varying(256)")
                                .HasColumnName("address_street");

                            b1.HasKey("WarehouseId");

                            b1.ToTable("warehouses");

                            b1.WithOwner()
                                .HasForeignKey("WarehouseId");
                        });

                    b.OwnsOne("MyWay.Core.Common.ValueObjects.ContactInfo", "ContactInfo", b1 =>
                        {
                            b1.Property<Guid>("WarehouseId")
                                .HasColumnType("uuid");

                            b1.Property<string>("ContactName")
                                .HasMaxLength(256)
                                .HasColumnType("character varying(256)")
                                .HasColumnName("contact_person_name");

                            b1.Property<string>("Email")
                                .HasMaxLength(320)
                                .HasColumnType("character varying(320)")
                                .HasColumnName("contact_email");

                            b1.Property<string>("Phone")
                                .HasMaxLength(64)
                                .HasColumnType("character varying(64)")
                                .HasColumnName("contact_phone");

                            b1.HasKey("WarehouseId");

                            b1.ToTable("warehouses");

                            b1.WithOwner()
                                .HasForeignKey("WarehouseId");
                        });

                    b.Navigation("Address")
                        .IsRequired();

                    b.Navigation("ContactInfo");
                });

            modelBuilder.Entity("MyWay.Core.Waybills.Waybill", b =>
                {
                    b.OwnsOne("MyWay.Core.Common.ValueObjects.CargoDetails", "CargoDetails", b1 =>
                        {
                            b1.Property<Guid>("WaybillId")
                                .HasColumnType("uuid");

                            b1.Property<string>("Description")
                                .HasMaxLength(1000)
                                .HasColumnType("character varying(1000)")
                                .HasColumnName("cargo_description");

                            b1.Property<decimal?>("HeightCm")
                                .HasPrecision(18, 3)
                                .HasColumnType("numeric(18,3)")
                                .HasColumnName("cargo_height_cm");

                            b1.Property<bool>("IsFragile")
                                .HasColumnType("boolean")
                                .HasColumnName("cargo_is_fragile");

                            b1.Property<decimal?>("LengthCm")
                                .HasPrecision(18, 3)
                                .HasColumnType("numeric(18,3)")
                                .HasColumnName("cargo_length_cm");

                            b1.Property<string>("Name")
                                .IsRequired()
                                .HasMaxLength(256)
                                .HasColumnType("character varying(256)")
                                .HasColumnName("cargo_name");

                            b1.Property<bool>("RequiresRefrigeration")
                                .HasColumnType("boolean")
                                .HasColumnName("cargo_requires_refrigeration");

                            b1.Property<decimal?>("VolumeM3")
                                .HasPrecision(18, 3)
                                .HasColumnType("numeric(18,3)")
                                .HasColumnName("cargo_volume_m3");

                            b1.Property<decimal>("WeightKg")
                                .HasPrecision(18, 3)
                                .HasColumnType("numeric(18,3)")
                                .HasColumnName("cargo_weight_kg");

                            b1.Property<decimal?>("WidthCm")
                                .HasPrecision(18, 3)
                                .HasColumnType("numeric(18,3)")
                                .HasColumnName("cargo_width_cm");

                            b1.HasKey("WaybillId");

                            b1.ToTable("waybills");

                            b1.WithOwner()
                                .HasForeignKey("WaybillId");
                        });

                    b.OwnsOne("MyWay.Core.Common.ValueObjects.Address", "DeliveryAddress", b1 =>
                        {
                            b1.Property<Guid>("WaybillId")
                                .HasColumnType("uuid");

                            b1.Property<string>("ApartmentOrOffice")
                                .HasMaxLength(64)
                                .HasColumnType("character varying(64)")
                                .HasColumnName("delivery_apartment_or_office");

                            b1.Property<string>("City")
                                .IsRequired()
                                .HasMaxLength(128)
                                .HasColumnType("character varying(128)")
                                .HasColumnName("delivery_city");

                            b1.Property<string>("Country")
                                .IsRequired()
                                .HasMaxLength(128)
                                .HasColumnType("character varying(128)")
                                .HasColumnName("delivery_country");

                            b1.Property<string>("House")
                                .IsRequired()
                                .HasMaxLength(64)
                                .HasColumnType("character varying(64)")
                                .HasColumnName("delivery_house");

                            b1.Property<decimal?>("Latitude")
                                .HasPrecision(9, 6)
                                .HasColumnType("numeric(9,6)")
                                .HasColumnName("delivery_latitude");

                            b1.Property<decimal?>("Longitude")
                                .HasPrecision(9, 6)
                                .HasColumnType("numeric(9,6)")
                                .HasColumnName("delivery_longitude");

                            b1.Property<string>("PostalCode")
                                .HasMaxLength(32)
                                .HasColumnType("character varying(32)")
                                .HasColumnName("delivery_postal_code");

                            b1.Property<string>("Region")
                                .HasMaxLength(128)
                                .HasColumnType("character varying(128)")
                                .HasColumnName("delivery_region");

                            b1.Property<string>("Street")
                                .IsRequired()
                                .HasMaxLength(256)
                                .HasColumnType("character varying(256)")
                                .HasColumnName("delivery_street");

                            b1.HasKey("WaybillId");

                            b1.ToTable("waybills");

                            b1.WithOwner()
                                .HasForeignKey("WaybillId");
                        });

                    b.OwnsOne("MyWay.Core.Common.ValueObjects.Address", "PickupAddress", b1 =>
                        {
                            b1.Property<Guid>("WaybillId")
                                .HasColumnType("uuid");

                            b1.Property<string>("ApartmentOrOffice")
                                .HasMaxLength(64)
                                .HasColumnType("character varying(64)")
                                .HasColumnName("pickup_apartment_or_office");

                            b1.Property<string>("City")
                                .IsRequired()
                                .HasMaxLength(128)
                                .HasColumnType("character varying(128)")
                                .HasColumnName("pickup_city");

                            b1.Property<string>("Country")
                                .IsRequired()
                                .HasMaxLength(128)
                                .HasColumnType("character varying(128)")
                                .HasColumnName("pickup_country");

                            b1.Property<string>("House")
                                .IsRequired()
                                .HasMaxLength(64)
                                .HasColumnType("character varying(64)")
                                .HasColumnName("pickup_house");

                            b1.Property<decimal?>("Latitude")
                                .HasPrecision(9, 6)
                                .HasColumnType("numeric(9,6)")
                                .HasColumnName("pickup_latitude");

                            b1.Property<decimal?>("Longitude")
                                .HasPrecision(9, 6)
                                .HasColumnType("numeric(9,6)")
                                .HasColumnName("pickup_longitude");

                            b1.Property<string>("PostalCode")
                                .HasMaxLength(32)
                                .HasColumnType("character varying(32)")
                                .HasColumnName("pickup_postal_code");

                            b1.Property<string>("Region")
                                .HasMaxLength(128)
                                .HasColumnType("character varying(128)")
                                .HasColumnName("pickup_region");

                            b1.Property<string>("Street")
                                .IsRequired()
                                .HasMaxLength(256)
                                .HasColumnType("character varying(256)")
                                .HasColumnName("pickup_street");

                            b1.HasKey("WaybillId");

                            b1.ToTable("waybills");

                            b1.WithOwner()
                                .HasForeignKey("WaybillId");
                        });

                    b.OwnsOne("MyWay.Core.Common.ValueObjects.DateRange", "TripPeriod", b1 =>
                        {
                            b1.Property<Guid>("WaybillId")
                                .HasColumnType("uuid");

                            b1.Property<DateTimeOffset>("EndAt")
                                .HasColumnType("timestamp with time zone")
                                .HasColumnName("period_end");

                            b1.Property<DateTimeOffset>("StartAt")
                                .HasColumnType("timestamp with time zone")
                                .HasColumnName("period_start");

                            b1.HasKey("WaybillId");

                            b1.ToTable("waybills");

                            b1.WithOwner()
                                .HasForeignKey("WaybillId");
                        });

                    b.Navigation("CargoDetails")
                        .IsRequired();

                    b.Navigation("DeliveryAddress")
                        .IsRequired();

                    b.Navigation("PickupAddress")
                        .IsRequired();

                    b.Navigation("TripPeriod")
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
